name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
      
    - name: Publish
      run: dotnet publish TaniePiwoClient/TaniePiwoClient.csproj -o release --nologo
    
    # changes the base-tag in index.html from '/' to 'TaniePiwoClient' to match GitHub Pages repository subdirectory
    #- name: Change base-tag in index.html from / to TaniePiwoClient
    #  run: sed -i 's/<base href="\/" \/>/<base href="\/TaniePiwoClient\/" \/>/g' release/wwwroot/index.html
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
